version: '3'
services:
    jenkins:
        image: jenkinsci/blueocean
        user: root  
        ports:
            - 80:8080
            # Do not map the JNLP port for security reasons
            # - 50000:50000
        volumes:
        - jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
volumes:
     jenkins:
