version: "3"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile_test
    depends_on:
      - build
  build:
    image: jest-test
    build:
      context: .
      dockerfile: Dockerfile_build
